### PR TITLE
Wait for on-boot apt run to finish, install ansible from pypi.

### PR DESCRIPTION
**Pull request by mikalstill**

### CODE REVIEW

**Review by mandoonandy — APPROVED** [review]
LGTM  Nice find.

**Comment by mikalstill** [comment]
I added a second lock file to the check...

**Comment by mikalstill** [comment]
Don't merge this, I am having troubles making it reliable.

**Comment by mikalstill** [comment]
Now ready for review again, CI failures are unrelated to this change.

**Review by mandoonandy — APPROVED** [review]
LGTM

**Pull request merged**
