### PR TITLE
Limit the length of interface names.

### LINKED ISSUE #355: We need to limit the length of interface names we create
```
Oct  7 10:36:46 marvin sh[779732]: Traceback (most recent call last):
Oct  7 10:36:46 marvin sh[779732]:   File "/usr/local/bin/sf-daemon", line 8, in <module>
Oct  7 10:36:46 marvin sh[779732]:     sys.exit(main())
Oct  7 10:36:46 marvin sh[779732]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/daemons/main.py", line 134, in main
Oct  7 10:36:46 marvin sh[779732]:     util.execute(None,
Oct  7 10:36:46 marvin sh[779732]:   File "/usr/local/lib/python3.8/dist-packages/shakenfist/util.py", line 242, in execute
Oct  7 10:36:46 marvin sh[779732]:     return processutils.execute(
Oct  7 10:36:46 marvin sh[779732]:   File "/usr/local/lib/python3.8/dist-packages/oslo_concurrency/processutils.py", line 431, in execute
Oct  7 10:36:46 marvin sh[779732]:     raise ProcessExecutionError(exit_code=_returncode,
Oct  7 10:36:46 marvin sh[779732]: oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
Oct  7 10:36:46 marvin sh[779732]: Command: ip link add phy-br-enx00e04c683700 type bridge
Oct  7 10:36:46 marvin sh[779732]: Exit code: 2
Oct  7 10:36:46 marvin sh[779732]: Stdout: ''
Oct  7 10:36:46 marvin sh[779732]: Stderr: 'Error: Attribute failed policy validation.\n'
Oct  7 10:36:46 marvin systemd[1]: sf.service: Main process exited, code=exited, status=1/FAILURE
Oct  7 10:36:46 marvin systemd[1]: sf.service: Failed with result 'exit-code'.
```

Which is easy to recreate:

```
$ sudo ip link add phy-br-enx00e04c683700 type bridge
Error: Attribute failed policy validation.
```

And is because the interface name is too long:

```
$ sudo ip link del phy-br-enx00e04
```

We've known for a long time that interface names are limited to 16 characters, but then we sleep walked into this.

### PR DESCRIPTION
**Pull request by mikalstill**
Fixes #355.

### CODE REVIEW

**Review by mandoonandy — APPROVED** [review]
I would prefer a longer term solution. I don't think we should design warnings into the code that an operator cannot fix.

If you want to merge to keep moving, I'm still fine. I'll leave it to you to hit merge. :-)

**Comment by mikalstill** [comment]
So I am unsure we can fix this ourselves. The issue is the name of the interface on my machine is enx00e04c683700 which is very close to the maximum length already. Do you have a proposed alternative?

**Comment by mandoonandy** [comment]
This is frustrating - I haven't seen the MAC in the interface name before. (I deleted all my hand wavy "what-ifs" comment concerning multiple NIC's with sequential MAC addresses - our usage should not be an issue).

Just thinking aloud?? We could do something funky like shorten the beginning of the MAC since that is the manufacturer code, leaving the trailing bytes which are generally more unique? But that is still not robust in the face of other naming schemes.

My actual suggestion is to reduce the message level to `info`. The message is not warning of a problem, it's really just an FYI.

**Comment by mikalstill** [comment]
I'll reduce the message level and I guess we just keep pondering the greater issue for now.

**Pull request merged**
