### PR TITLE
Update docs for v0.3.

### PR DESCRIPTION
**Pull request by mikalstill**

### CODE REVIEW

**Review by mandoonandy — COMMENTED** [review]
The /docs location is okay, but do we still need a file called README?

**Comment by mikalstill** [comment]
So, the README.md file is rendered on github.com, so I do think we need something there which redirects people to the website.

**Comment by mandoonandy** [comment]
That was particularly unclear of me. I was trying to say, I think we should have more of a sales piece in the README but I'll merge this now and leave that for further discussion.

**Comment by mandoonandy** [comment]
Also, the Source code link is self-referencing and unnecessary.

**Pull request merged**
