### PR TITLE
Docs update

### PR DESCRIPTION
**Pull request by jackadamson**
Move contents of shakenfist/website into docs directory. Build with mkdocs-material. Neatened up documentation wording along the way.

Hosted build: https://jackadamson.github.io/shakenfist/

Docs about publishing the website: https://jackadamson.github.io/shakenfist/development/updating_docs/

Key features:
- Pretty theme
- Search capabilities
- Edit button in docs to go to repo
- One less repository
- **Really pretty theme**

## Screenshots

Overview
Overview

Side Nav Bar
Side Nav Bar

Searchbar
Searchbar

Auto Linking of Issues and PRs
Auto Linking of Issues and PRs

### CODE REVIEW

**Comment by mikalstill** [comment]
This is very pretty, but I think it means we can't use github's hosting for the site any more. Is that correct or am I confused?

**Comment by jackadamson** [comment]
> This is very pretty, but I think it means we can't use github's hosting for the site any more. Is that correct or am I confused?

This works with Github pages hosting. To deploy to GitHub pages just run `mkdocs gh-deploy`.

I currently have it hosted on my GitHub pages at https://jackadamson.github.io/shakenfist/

**Comment by jackadamson** [comment]
And the `CNAME` file in the docs directory is automatically included

**Comment by jackadamson** [comment]
Also, if we want CI to automatically deploy the docs, we can use this GitHub action:
https://github.com/marketplace/actions/deploy-mkdocs

**Review by mikalstill — APPROVED** [review]
LGTM, but I think I'd like to see the pipeline added as well please.

**Pull request merged**
