### PR TITLE
When testing poweroff wait for poweroff detection

### LINKED ISSUE #392: TestStateChanges.test_lifecycle_events issues poweron before poweroff detected
```
| 2020-10-10 08:38:08.709242 | sfci-2lvo2j.c.mikal-269605.internal |          poweroff          |           complete          |          None         |                   None                  |

| 2020-10-10 08:38:28.127753 | sfci-2lvo2j.c.mikal-269605.internal |            api             |           poweron           |          None         |                   None                  |

| 2020-10-10 08:38:48.797445 | sfci-2lvo2j.c.mikal-269605.internal |     detected poweroff      |           complete          |          None         |                   None                  |
```

### PR DESCRIPTION
**Pull request by mandoonandy**
Resolves #392

### CODE REVIEW

**Comment by mandoonandy** [comment]
Maybe we should ensure this properly handled in the API? 

First thought is to reject `poweron` requests during `poweroff` cycle. (Keep it simple rather than being fancy.)

**Comment by mikalstill** [comment]
I do like the idea of refusing to change a state if the instance is already in a transition state.

**Review by mikalstill — APPROVED** [review]
LGTM

**Comment by mikalstill** [comment]
CI failure looks like a flakey network test to me:

```
shakenfist_ci.tests.test_state_changes.TestStateChanges.test_lifecycle_events
-----------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    Traceback (most recent call last):

      File "/tmp/workspace/shakenfist_PR-393/deploy/shakenfist_ci/tests/test_state_changes.py", line 65, in test_lifecycle_events
    self._test_ping(inst['uuid'], self.net['uuid'], ip, True, 10)

      File "/tmp/workspace/shakenfist_PR-393/deploy/shakenfist_ci/base.py", line 120, in _test_ping
    shell=True, check_exit_code=[0, 1])

      File "/usr/local/lib/python3.6/dist-packages/oslo_concurrency/processutils.py", line 434, in execute
    cmd=sanitized_cmd)

    oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
Command: sudo ip netns exec 949b2aa9-1cb9-421c-b01e-3471a00f7aae ping -c 10 192.168.242.21
Exit code: 2
Stdout: ''
Stderr: 'connect: Network is unreachable\n'
```

**Pull request merged**
