### PR TITLE
Fix sf-upgrade fail while deleting mesh events

### LINKED ISSUE #290: Deploy fails on sf-upgrade
etcdctl still fails due to gRPC size limitation.

### PR DESCRIPTION
**Pull request by mandoonandy**
Resolves #290 

Is this deletion code still a thing that's required? Anyway this should avoid failures during deploy.

### CODE REVIEW

**Comment by mandoonandy** [comment]
Sadly it blocked my deploy test.

**Comment by mandoonandy** [comment]
How about I change it to delete all currently targeted events and then delete the remain events keeping the last 50 events per network?

**Comment by mikalstill** [comment]
I like that idea.

**Comment by mandoonandy** [comment]
Since sf-syd is probably the only cloud and it does not have ensure mesh events any more, changed the spec to just last 50 events.
Also, we may not even need to this at all, I just made a quick code change.

**Pull request merged**
