### PR TITLE
Add a simple backup and restore tool for etcd, this is used for upgrade CI.

### PR DESCRIPTION
**Pull request by mikalstill**

### CODE REVIEW

**Review by mandoonandy — APPROVED** [review]
Nice tool

**Comment by mikalstill** [comment]
I'm a little bit proud of the use of tarballs as a storage format. Its actually way simpler to use than the real etcd snapshot tool.

**Comment by mikalstill** [comment]
CI failures seem unrelated.

**Review by mandoonandy — APPROVED** [review]
LGTM

**Pull request merged**
