### PR TITLE
Remove old fashioned CI from deployandtest.

### PR DESCRIPTION
**Pull request by mikalstill**
This CI really has passed its prime. We should just move it all to the new thing.

### CODE REVIEW

**Review by mandoonandy — APPROVED** [review]
Looks GREAT to me

**Comment by mikalstill** [comment]
That's enough for tonight, but you get the idea.

**Comment by mikalstill** [comment]
This is now complete. There are lots more tests to add, but that's a problem for another review.

**Review by mandoonandy — APPROVED** [review]
Brilliant effort. CI passes!

**Pull request merged**
