### PR TITLE
First cut of a simple load tester

### PR DESCRIPTION
**Pull request by mandoonandy**
This is a quick load tester that starts Ubuntu instances and waits for them to each call home.
If this is useful, I can tidy it up and we can extend it. (Add more doc, clean up code, etc.) If not we can junk it.

Initially I placed it in the ```deploy``` repo but I think it more naturally belongs with the actual thing it tests.
```
andy@arwen:/andy/Projects/5d/sf/shakenfist/tools/load-testing/callcentre$ ./callcentre --help
Call Centre will:
  Create a unique namespace
  Create a network within that namespace
  Start instances in the namespace
  Wait for each instance to call back via HTTP on port 8089
  Delete each instance that has called back
  When all instances have called back, delete the network
  Delete the namespace

If the test fails, the "sf-client namespace clean" command can be used

Usage:
  callcentre [flags]

Flags:
      --cloudinit string   Cloud init phone home YAML filename (default "phone-home.yaml")
      --config string      Call Centre config file (default is callcentre.yaml)
      --count int          Number of instances to start
      --cpu int            Instance CPU count
  -h, --help               help for callcentre
      --ip string          This servers reachable IP address from within the instances
      --memory int         Instance Memory size in MB
```
A simple run looks like this:
```
andy@arwen:/andy/Projects/5d/sf/shakenfist/tools/load-testing/callcentre$ ./callcentre --cpu 1 --count 3 --memory 1024 --ip 192.168.72.150
CPU=1  Memory=1024
Starting 3 instances...

Creating new load test namespace: loadtest-9139e342

Instances: Started=0 Callbacks=0 Outstanding=0
  Started Instance   0: ca914f8a-2dde-4ca5-b8b2-d25c31bb0a8b  Node: sf-2  ConsolePort: 49569

--> All start requests sent
  Started Instance   1: 70aac03e-bddc-4fa6-9535-78eac057e5e1  Node: sf-2  ConsolePort: 39260
  Started Instance   2: 4b0387eb-6c55-4914-9038-759959c15b2a  Node: sf-2  ConsolePort: 45741

Instances: Started=3 Callbacks=0 Outstanding=3
  1: 70aac03e-bddc-4fa6-9535-78eac057e5e1  sf-2
  2: 4b0387eb-6c55-4914-9038-759959c15b2a  sf-2
  0: ca914f8a-2dde-4ca5-b8b2-d25c31bb0a8b  sf-2

Instances: Started=3 Callbacks=0 Outstanding=3
  0: ca914f8a-2dde-4ca5-b8b2-d25c31bb0a8b  sf-2
  1: 70aac03e-bddc-4fa6-9535-78eac057e5e1  sf-2
  2: 4b0387eb-6c55-4914-9038-759959c15b2a  sf-2

[snip - repeated output]

Instances: Started=3 Callbacks=0 Outstanding=3
  0: ca914f8a-2dde-4ca5-b8b2-d25c31bb0a8b  sf-2
  1: 70aac03e-bddc-4fa6-9535-78eac057e5e1  sf-2
  2: 4b0387eb-6c55-4914-9038-759959c15b2a  sf-2

Instances: Started=3 Callbacks=0 Outstanding=3
  2: 4b0387eb-6c55-4914-9038-759959c15b2a  sf-2
  0: ca914f8a-2dde-4ca5-b8b2-d25c31bb0a8b  sf-2
  1: 70aac03e-bddc-4fa6-9535-78eac057e5e1  sf-2
    Received callback: 0
    Received callback: 1

Instances: Started=3 Callbacks=2 Outstanding=1
  2: 4b0387eb-6c55-4914-9038-759959c15b2a  sf-2
    Received callback: 2

SUCCESS - All instances have phoned home
andy@arwen:/andy/Projects/5d/sf/shakenfist/tools/load-testing/callcentre$ 

```

### CODE REVIEW

**Comment by mandoonandy** [comment]
New features and new help
```
Call Centre will:
  Create a unique namespace
  Create a network within that namespace
  Start instances in the namespace
  Wait for each instance to call back via HTTP on port 8089
  When all instances have called back, delete all instances
  Delete the network
  Delete the namespace

If the test fails, the "sf-client namespace clean" command can be used

Usage:
  callcentre [flags]

Flags:
      --cloudinit string   Cloud init phone home YAML filename (default "phone-home.yaml")
      --config string      Call Centre config file (default is callcentre.yaml)
      --cpu int            Instance CPU count
      --delCallback        Delete instance immediately after it's callback
      --delay int          Delay between attempting to start instances (default 1)
  -h, --help               help for callcentre
      --ip string          This servers reachable IP address from within the instances
      --load int           Number of instances to start
      --memory int         Instance Memory size in MB
```

**Comment by mandoonandy** [comment]
A separate repo would be the most convenient due to golang issues but we seem to have a lot of repos...
I vote for a separate repo.
You?

**Comment by mikalstill** [comment]
Separate repo for the win. Do you have permissions to make one?

**Comment by mandoonandy** [comment]
Done. New repo at https://github.com/shakenfist/loadtest

**Pull request closed without merging**
